### ISSUE TITLE
Doesn't work with mongodb

### ISSUE THREAD

**Issue by MarcusSjolin** [lexik/LexikCurrencyBundle#14]
It seems like it doesn't seem work with mongodb as the service name is no longer doctrine, it probably is doctrine_mongodb. I have not configured donctrine, only donctrine_mongodb in my config.yml.

Is this something that is a bug, or is this me who have misconfigured this?

**Comment by gabma** [comment]
Hi, anyone got any news on this part ? Would it need a lot of rewriting ?
