### ISSUE TITLE
Service lexik_currency.currency_extension is not public

### ISSUE THREAD

**Issue by tormit** [lexik/LexikCurrencyBundle#29]
Could you make lexik_currency.currency_extension service public, so it's methods could be used anywhere in the code. 
Or make converting/formatting as single service and use it in Twig.

**Comment by tormit** [comment]
You may merge my pull request.

**Comment by cedric-g** [comment]
If you need to set the service public I suppose you want to format some values, but to me the best would be to move the format process into a service and make the extension use this service (as for conversion).

**Comment by tormit** [comment]
Yes. I'll extract convert/format as separate services in my fork.

**Comment by cedric-g** [comment]
I extracted the logic to format into the `lexik_currency.formatter` service.
