### ISSUE TITLE
Namespace change should not go into patch release

### ISSUE THREAD

**Issue by ryzy** [lexik/LexikCurrencyBundle#36]
Hi

FYI, so you're bit more careful with versioning.

That change https://github.com/lexik/LexikCurrencyBundle/commit/304eda7c766d1a33e650854c9f59bd678c4ce12a introduced after `1.2.3` and included in `1.2.4` is a breaking change because it introduces namespace change.

If you follow semantic versioning, that SHOULD NOT go into PATCH release. You should at least change MINOR version or even consider MAJOR version update. Or simply not change the namespace ;-)

Just a thought... and thanks for that awesome bundle!
Marcin

**Comment by cedric-g** [comment]
Hi, yes you're right. I've created new tags on several bundles at the same time and I simply forgot I changed a namespace when I created the tag for this one.
