### ISSUE TITLE
Deprecated Twig_Filter_Method in CurrencyExtension

### ISSUE THREAD

**Issue by etioun** [lexik/LexikCurrencyBundle#40]
Hi guys !

I'm getting the following warnings : 

**The Twig_Filter class is deprecated since version 1.12 and will be removed in 2.0. Use Twig_SimpleFilter instead.** 

**Using an instance of "Twig_Filter_Method" for filter "currency_convert" is deprecated. Use Twig_SimpleFilter instead.**
...

Have you planned to do to something about it ?

**Comment by cedric-g** [comment]
Hi, I've updated the Twig extension.

**Comment by etioun** [comment]
Cool Thanks !! I'll close this issue when you release !
