### ISSUE TITLE
 Can't find currency: "EGP" 

### ISSUE THREAD

**Issue by ahmadGamal** [lexik/LexikCurrencyBundle#47]
I'm trying to set default currency as' EGP'  Egypt pound in config file
`
lexik_currency:
    currencies:
        default: EGP       
        managed: [EGP, USD, EUR, ...]
`

 but it give me 
 Can't find currency: "EGP" 

How can i set Egyptian pound ? 

Thanks

**Comment by jdambacher** [comment]
The default adapter only works with some "main" currencies, because the data comes from the ECB.
You could use my custom yahoo adapter instead. It should work with EGP.
