### ISSUE TITLE
Symfony3 Support

### ISSUE THREAD

**Issue by medevphp** [lexik/LexikCurrencyBundle#52]
Hi,
Are there any plan to support Symfony3?

**Comment by cedric-g** [comment]
Hi, the tests suite run on SF 2.8 and 3.0 so it should work, did you get any errors with SF 3.x ?

**Comment by medevphp** [comment]
Composer install requires symfony ~2.7

**Comment by cedric-g** [comment]
Use the `master` branch, it's not tagged yet.

**Comment by julestruong** [comment]
Can't you tag it ?
